### PR TITLE
fixes #251 regarding issue with non-ascii characters, mainly for irc bac...

### LINKED ISSUE #251: irc backend blows up on non-ascii data
Traced the problem to `build_text_html_message_pair()` in `backends/base.py`

Adding an `except UnicodeEncodeError:` makes it work:

```python
def build_text_html_message_pair(source):
    node = None
    text_plain = None

    try:
        node = ET.XML(source)
        text_plain = xhtml2txt(source)
    except ParseError, ee:
        if source.strip():  # avoids keep alive pollution
            logging.debug(u'Could not parse [%s] as XHTML-IM, assume pure text Parsing error = [%s]' % (source, ee))
            text_plain = source
    except UnicodeEncodeError:
        text_plain = source
    return text_plain, node
```

### PR DESCRIPTION
**Pull request by sijis**
This should fix issue #251.

I just converted his output to a true PR.

### CODE REVIEW

**Comment by gbin** [comment]
It looks like it broke a test, can you check why ?

**Comment by sijis** [comment]
I've run the test locally, using python 3.3.2 and they pass. Looking closely at the error, test seem to fail on python 3.4.2. I'll load that up and retest it with that version.

**Comment by sijis** [comment]
I just rant the test in py 3.4.2 on and it was all OK (except some W503 errors, not related to this PR)
```
(errbot) [vagrant@centos7-vm err]$ python run_tests.py 
============================================================================= test session starts ==============================================================================
platform linux -- Python 3.4.2 -- py-1.4.26 -- pytest-2.6.4
plugins: xdist
collected 88 items 

tests/base_backend_tests.py ..........................
tests/commands_tests.py .................
tests/muc_tests.py ......
tests/plugin_management_tests.py ..
tests/streaming_test.py .
tests/utils_tests.py .........................
tests/webhooks_tests.py ...........

========================================================================= 88 passed in 278.02 seconds ==========================================================================
./errbot/errBot.py:640:21: W503 line break before binary operator
                    and not command._err_command_hidden
                    ^
./errbot/errBot.py:641:21: W503 line break before binary operator
                    and (not self.bot_config.HIDE_RESTRICTED_COMMANDS or may_access_command(name))
                    ^
./errbot/errBot.py:654:17: W503 line break before binary operator
                and (not self.bot_config.HIDE_RESTRICTED_COMMANDS or may_access_command(name))
                ^
./errbot/errBot.py:714:17: W503 line break before binary operator
                and command.__doc__ is not None
                ^
./errbot/errBot.py:715:17: W503 line break before binary operator
                and args.lower() in command.__doc__.lower()
                ^
./errbot/errBot.py:716:17: W503 line break before binary operator
                and name != 'help'
                ^
./errbot/errBot.py:717:17: W503 line break before binary operator
                and not command._err_command_hidden
                ^
./errbot/backends/base.py:1139:17: W503 line break before binary operator
                and not command._err_command_hidden
                ^
./errbot/backends/base.py:1160:17: W503 line break before binary operator
                and in_reply_to
                ^
./errbot/backends/base.py:1161:17: W503 line break before binary operator
                and nick_reply
                ^
./errbot/backends/base.py:1162:17: W503 line break before binary operator
                and groupchat_nick_reply):
                ^
11      W503 line break before binary operator
(errbot) [vagrant@centos7-vm err]$ 
```

**Comment by gbin** [comment]
I fixed those, you can git rebase master and it should be good to go :)

**Pull request merged**
