### PR TITLE
Slack: Add new users to the local user cache.

### PR DESCRIPTION
**Pull request by gbin**

### CODE REVIEW

**Comment by zoni** [comment]
I think we should fix this upstream by letting SlackClient [process it here](https://github.com/slackhq/python-slackclient/blob/master/slackclient/_client.py#L42-L49), instead of working around it ourselves. That way it just works by default for anyone using that library.

**Comment by zoni** [comment]
It might also be good to handle the [user_change](https://api.slack.com/events/user_change) event at the same time as well.

**Comment by gbin** [comment]
@zoni completely agree, this is weird that the binding doesn't do it by itself. I gonna put a bug on their bindings.

**Comment by gbin** [comment]
@zoni reported it https://github.com/slackhq/python-slackclient/issues/33

**Comment by gbin** [comment]
No reaction from them, I'll merge this one for now and revisit once they improved their implementation.

**Pull request merged**
