### PR TITLE
Errbot.net fixes - work in progress

### PR DESCRIPTION
**Pull request by sijis**
Including small updates to the website.
* broken links
* fixing sphinx build error
* formatting / copy editing

*work in progress*

Sijis

### CODE REVIEW

**Comment by zoni** [comment]
Thanks for taking up the inglorious task of improving documentation! :smiling_imp: 

Would you mind basing your branch off `errbot.net` though, and opening your PR on that branch instead, also? That way I can publish it straight away once it's ready for merging, otherwise it will have to wait until the next release of Err to PyPI before I can do so (this ensures the API documentation on http://errbot.net matches that of the version on PyPI).

**Comment by sijis** [comment]
Sure. 

Will these changes in errbot.net branch get merged with master? I've been hacking at the source for some if the docs. I'm just afraid that those may be lost.

**Comment by zoni** [comment]
Yes, this branch will be merged back into master also

**Comment by sijis** [comment]
will create properly.

**Pull request closed without merging**
