### PR TITLE
Support for case-insensitive file system (e.g. OS X)

### PR DESCRIPTION
**Pull request by gugu**
+ fixed some bug

### CODE REVIEW

**Comment by gbin** [comment]
relative imports are nice especially if they fix something O o . Can you fix the PEP8 brackage so we can merge it ? thx !

**Comment by gugu** [comment]
Yes, you have errBot.py in errbot directory.

So when code `from errbot import PY2` runs in errbot/decorators.py:

* in linux, it imports PY2 from errbot/__init__.py
* in MacOS it tries to import PY2 from errbot/errBot.py

Sure, will fix PEP8 tomorrow morning

**Comment by gbin** [comment]
Ha ok, thx for the explanation !

**Comment by gugu** [comment]
fixed :)

**Pull request merged**
