### PR TITLE
Markdown

### PR DESCRIPTION
**Pull request by gbin**
Historically Err could only do pure unicode text or xhtml-im. Templates were added and the process was like this:
1. Err applies the html-im template with the result of a command
2. Ellrr tries to remake a text version of it by parsing the output of the command in html
3. A message gets created with body (the text version) and html (the html created from the template) 

As we added more and more backend, this become more and more pointless as no backend except xmpp support html-im.

This PR fixed that by first ripping out this old html logic completely.

Now the expected output of any command is *markdown extra*. Jinja2 templates are still used but their extension is .md instead of .html.

Err exposes some helpers to the backends to be able to make the most of the formatting from the markdown version.

Here is the test document rendered under different backends:

### Console
ansi

### Slack
slack

### Hipchat
hipchat

### Gitter
gitter

### CODE REVIEW

**Comment by zoni** [comment]
I'm just missing one thing, how are links formatted on the various back-ends?

**Comment by zoni** [comment]
Also, before we merge this, we should squash all the commits down to one I think, keep a cleaner history.

**Comment by gbin** [comment]
links are represented in the intermediate tree as A, I haven't tried they might be gobbled up in the process as it is.

**Comment by gbin** [comment]
Just merged the branch in a squashed commit.

**Comment by gbin** [comment]
@zoni I fixed on head the links for text rendering by putting them in parenthesis.

**Pull request closed without merging**
